name: Deploy para Producao

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Sincronizar FTP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          server-dir: ./
          
          exclude: |
            **/.git*
            **/.git*/**
            .env.example
            .github/**
            README.md
            .gitignore
