name: LisonTech

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
            .gitignore
            secure/config.env
            public_html/config.env
            public_html/.ftp-deploy-sync-state.json
            public_html/log_*.txt
            public_html/painel/api/log_*.txt
            public_html/storage/logs/**
